FROM ubuntu:22.04

# Yocto Host Dependencies
RUN apt-get update && apt-get install -y \
    gawk wget git diffstat unzip texinfo gcc-multilib \
    build-essential chrpath socat cpio python3 python3-pip \
    python3-pexpect xz-utils debianutils iputils-ping python3-git \
    python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python3-psyco \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /yocto
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]

